spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/info
    username: user
    password: password
  sql:
    init:
      mode: always
      # data-locations: classpath:schema.sql, classpath:data.sql

server:
  port: 8080