spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/info
    username: user
    password: password
  sql:
    init:
      mode: always
      # data-locations: classpath:schema.sql, classpath:data.sql
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  charset:
    console: "UTF-8"
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{0}){cyan} %clr(:){faint} %m%n"
  level:
    org.springframework: INFO

server:
  port: 8080